# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Garage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TabPrincipale = QtWidgets.QTabWidget(self.centralwidget)
        self.TabPrincipale.setGeometry(QtCore.QRect(20, 20, 751, 621))
        self.TabPrincipale.setMouseTracking(False)
        self.TabPrincipale.setTabPosition(QtWidgets.QTabWidget.North)
        self.TabPrincipale.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.TabPrincipale.setIconSize(QtCore.QSize(16, 16))
        self.TabPrincipale.setUsesScrollButtons(False)
        self.TabPrincipale.setTabBarAutoHide(False)
        self.TabPrincipale.setObjectName("TabPrincipale")
        self.TabAfficher = QtWidgets.QWidget()
        self.TabAfficher.setObjectName("TabAfficher")
        self.tableView = QtWidgets.QTableView(self.TabAfficher)
        self.tableView.setGeometry(QtCore.QRect(0, 110, 731, 481))
        self.tableView.setObjectName("tableView")
        self.lineEdit = QtWidgets.QLineEdit(self.TabAfficher)
        self.lineEdit.setGeometry(QtCore.QRect(100, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.labelNomPiece = QtWidgets.QLabel(self.TabAfficher)
        self.labelNomPiece.setGeometry(QtCore.QRect(20, 30, 71, 20))
        self.labelNomPiece.setTextFormat(QtCore.Qt.PlainText)
        self.labelNomPiece.setObjectName("labelNomPiece")
        self.pushButton = QtWidgets.QPushButton(self.TabAfficher)
        self.pushButton.setGeometry(QtCore.QRect(100, 70, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.TabPrincipale.addTab(self.TabAfficher, "")
        self.TabAjouter = QtWidgets.QWidget()
        self.TabAjouter.setObjectName("TabAjouter")
        self.TabPrincipale.addTab(self.TabAjouter, "")
        self.TabModifier = QtWidgets.QWidget()
        self.TabModifier.setObjectName("TabModifier")
        self.TabPrincipale.addTab(self.TabModifier, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TabPrincipale.setCurrentIndex(0)
        self.pushButton.clicked.connect(self.tableView.resizeColumnsToContents) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.TabPrincipale)
        MainWindow.setTabOrder(self.TabPrincipale, self.tableView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelNomPiece.setText(_translate("MainWindow", "Nom de pièce"))
        self.pushButton.setText(_translate("MainWindow", "Lancer laRechercher"))
        self.TabPrincipale.setTabText(self.TabPrincipale.indexOf(self.TabAfficher), _translate("MainWindow", "Rechercher"))
        self.TabPrincipale.setTabText(self.TabPrincipale.indexOf(self.TabAjouter), _translate("MainWindow", "Ajouter"))
        self.TabPrincipale.setTabText(self.TabPrincipale.indexOf(self.TabModifier), _translate("MainWindow", "Modifier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
