# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt\Garage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TabPrincipale = QtWidgets.QTabWidget(self.centralwidget)
        self.TabPrincipale.setGeometry(QtCore.QRect(20, 20, 751, 621))
        self.TabPrincipale.setMouseTracking(False)
        self.TabPrincipale.setTabPosition(QtWidgets.QTabWidget.North)
        self.TabPrincipale.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.TabPrincipale.setIconSize(QtCore.QSize(16, 16))
        self.TabPrincipale.setUsesScrollButtons(False)
        self.TabPrincipale.setTabBarAutoHide(False)
        self.TabPrincipale.setObjectName("TabPrincipale")
        self.TabRechercher = QtWidgets.QWidget()
        self.TabRechercher.setObjectName("TabRechercher")
        self.lineEdit = QtWidgets.QLineEdit(self.TabRechercher)
        self.lineEdit.setGeometry(QtCore.QRect(150, 30, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.labelNomPiece = QtWidgets.QLabel(self.TabRechercher)
        self.labelNomPiece.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.labelNomPiece.setTextFormat(QtCore.Qt.PlainText)
        self.labelNomPiece.setObjectName("labelNomPiece")
        self.pushButton_Recherche = QtWidgets.QPushButton(self.TabRechercher)
        self.pushButton_Recherche.setGeometry(QtCore.QRect(150, 70, 131, 31))
        self.pushButton_Recherche.setObjectName("pushButton_Recherche")
        self.tableWidget = QtWidgets.QTableWidget(self.TabRechercher)
        self.tableWidget.setGeometry(QtCore.QRect(10, 130, 731, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.TabPrincipale.addTab(self.TabRechercher, "")
        self.TabAjouter = QtWidgets.QWidget()
        self.TabAjouter.setObjectName("TabAjouter")
        self.TabPrincipale.addTab(self.TabAjouter, "")
        self.TabModifier = QtWidgets.QWidget()
        self.TabModifier.setObjectName("TabModifier")
        self.TabPrincipale.addTab(self.TabModifier, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TabPrincipale.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.pushButton_Recherche)
        MainWindow.setTabOrder(self.pushButton_Recherche, self.TabPrincipale)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelNomPiece.setText(_translate("MainWindow", "Nom de pièce"))
        self.pushButton_Recherche.setText(_translate("MainWindow", "Rechercher"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No. article"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pièce"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fournisseur"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantité en stock"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Emplacement"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date d\'aquisition"))
        self.TabPrincipale.setTabText(self.TabPrincipale.indexOf(self.TabRechercher), _translate("MainWindow", "Rechercher"))
        self.TabPrincipale.setTabText(self.TabPrincipale.indexOf(self.TabAjouter), _translate("MainWindow", "Ajouter"))
        self.TabPrincipale.setTabText(self.TabPrincipale.indexOf(self.TabModifier), _translate("MainWindow", "Modifier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
